- name: Install needed packages
  apt: name={{ item }} state=present
  with_items:
    - supervisor
    - python3
    - python3-pip
    - python3-venv
    - python-virtualenv

- name: Fetch code from github
  become_user: pi
  git:
    repo: https://github.com/davea/homesense-web.git
    dest: /home/pi/homesense-web
    accept_hostkey: yes
  notify:
    - reload supervisor

- name: Create/populate virtualenv
  become_user: pi
  pip:
    virtualenv: "/home/pi/homesense-web-venv"
    virtualenv_python: "/usr/bin/python3.5"
    requirements: "/home/pi/homesense-web/requirements.txt"
  notify:
    - reload supervisor

- name: Setup supervisor task
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/homesense-web.conf
    owner: root
    group: root
  notify:
    - reload supervisor
