- name: Rotate display correctly
  lineinfile:
    dest: /boot/config.txt
    line: lcd_rotate=2
  notify:
    - Restart machine
    - Wait for restart

- name: Disable SSH password logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: PasswordAuthentication no
  notify:
    - Restart machine
    - Wait for restart

- name: Install needed packages
  apt: name={{ item }}
  with_items:
    - unclutter

- name: Set up display parameters and Chromium kiosk
  template:
    src: autostart.j2
    dest: /home/pi/.config/lxsession/LXDE-pi/autostart
    owner: pi
    group: pi
  notify:
    - Restart machine
    - Wait for restart
