#!/usr/bin/env ansible-playbook
---
- name: Set up server
  hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Update APT
      apt: update_cache=yes cache_valid_time=86400
  roles:
    - display
    - server

  handlers:
  - name: Restart machine
    command: shutdown -r now "Reboot triggered by Ansible"
    async: 0
    poll: 0
    ignore_errors: true

  - name: Wait for restart
    local_action:
      module: wait_for
        host={{ inventory_hostname }}
        port=22
        delay=1
        timeout=300
    become: no
